import type { Metadata } from "next";
import { Atkinson_Hyperlegible_Next, Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { CONFIG } from "@/lib/config";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";

const fontHeading = Atkinson_Hyperlegible_Next({
  variable: "--font-heading",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  fallback: ["--font-normal"],
});

const fontNormal = Roboto({
  variable: "--font-normal",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: {
    default: CONFIG.app_name,
    template: ` % | ${CONFIG.app_name}`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", fontHeading.variable, fontNormal.variable)}>
      <SessionProvider>
        <body className="flex min-h-full flex-col">
          {children}
          <Toaster />
        </body>
      </SessionProvider>
    </html>
  );
}
