import type { Metadata } from "next";
import { Atkinson_Hyperlegible, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { CONFIG } from "@/lib/config";

const fontHeading = Atkinson_Hyperlegible({
  variable: "--font-heading",
  weight: ["400", "700"],
});

const fontNormal = Inter({
  variable: "--font-normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: CONFIG.app_name,
    template: ` % | ${CONFIG.app_name}`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", fontHeading.variable, fontNormal.variable)}>
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
